### ISSUE TITLE
python issue - global name 'sys' is not defined

### ISSUE THREAD

**Issue by eze1981** [ceharvs/mabm#1]
Hi,

I'm trying to test MABM inside a Docker container based on Ubuntu and installed the following dependencies:
- mpich
- mpi4py
- numpy
- argparse
- psutil (it should be included in the README.md file)

This is my command line:
```mpiexec -np 2 python rumor-model-main.py 20 0.5```

And this is the error message:

```
# mpiexec -np 2 python rumor-model-main.py 20 0.5
Initial Saturation: 	 18/40 	 = 0.4500Traceback (most recent call last):
  File "rumor-model-main.py", line 106, in <module>
    main()

  File "rumor-model-main.py", line 57, in main
Traceback (most recent call last):
  File "rumor-model-main.py", line 106, in <module>
        m.run()
main()
  File "rumor-model-main.py", line 57, in main
    m.run()
  File "/usr/src/mabm/mabm/model.py", line 352, in run
  File "/usr/src/mabm/mabm/model.py", line 352, in run
    while self.__mabm_time != sys.maxint:
NameError: global name 'sys' is not defined
    while self.__mabm_time != sys.maxint:
NameError: global name 'sys' is not defined
```

I'm trying to figure out if this is a problem with my python installation.  Are the examples working for you?

Regards

**Comment by ceharvs** [comment]
Issue has been resolved with importing sys in the mabm/model file.  in the latest update.
